// ════════════════════════════════════════════════════════
// Kaynak    : YARA-Rules Project
// Kural     : antidebug_antivm_index.yar
// Toplanma  : 2026-02-27T23:11:16.055923
// Orijinal  : https://github.com/Yara-Rules/rules/blob/master/antidebug_antivm_index.yar
// ════════════════════════════════════════════════════════

/*
Generated by Yara-Rules
On 12-04-2022
*/
include "./antidebug_antivm/antidebug_antivm.yar"
