// ════════════════════════════════════════════════════════
// Kaynak    : YARA-Rules Project
// Kural     : capabilities_index.yar
// Toplanma  : 2026-02-27T23:11:16.189300
// Orijinal  : https://github.com/Yara-Rules/rules/blob/master/capabilities_index.yar
// ════════════════════════════════════════════════════════

/*
Generated by Yara-Rules
On 12-04-2022
*/
include "./capabilities/capabilities.yar"
