// ════════════════════════════════════════════════════════
// Kaynak    : YARA-Rules Project
// Kural     : crypto_index.yar
// Toplanma  : 2026-02-27T23:11:16.322256
// Orijinal  : https://github.com/Yara-Rules/rules/blob/master/crypto_index.yar
// ════════════════════════════════════════════════════════

/*
Generated by Yara-Rules
On 12-04-2022
*/
include "./crypto/crypto_signatures.yar"
